# ===================== Project: Ansible Sway =====================
- name: Ensure projects directory exists
  file:
    path: "{{ ansible_env.HOME }}/projects"
    state: directory
    mode: '0755'
  tags:
    - prj-ansible-i3

- name: Clone Ansible i3 repository
  git:
    repo: 'git@github.com:fabrizioanichini/ansible-i3.git'
    dest: "{{ ansible_env.HOME }}/projects/ansible-i3"
    version: main
    accept_hostkey: yes
  environment:
    GIT_SSH_COMMAND: "ssh -vvv"
  register: git_clone_result
  tags:
    - prj-ansible-i3

- name: Debug Git clone result
  debug:
    var: git_clone_result
  tags:
    - prj-ansible-i3

