# ===================== Core Task: System Packages =====================
- name: Ensure system utility packages are installed
  become: yes
  pacman:
    name:
      - man-db
      - openssh
    state: present
    update_cache: yes
  tags:
    - packages

# ===================== Core Task: Flow Packages =====================
- name: Ensure flow utility packages are installed
  become: yes
  pacman:
    name:
      - vim 
      - tmux 
      - rxvt-unicode
    state: present
    update_cache: yes
  tags:
    - packages

# ===================== Core Task: i3 Packages =====================
- name: Ensure i3 packages are installed
  become: yes
  pacman:
    name:
      - xorg-server
      - xorg-xinit 
    state: present
    update_cache: yes
  tags:
    - packages

# ===================== Core Task: UI Applications =====================
- name: Ensure UI application packages are installed
  become: yes
  pacman:
    name:
      - ttf-jetbrains-mono
      - i3-wm
      - i3status
      - dmenu
      - qutebrowser
    state: present
    update_cache: yes
  tags:
    - packages

# ===================== Core Task: Dotfiles =====================
- name: Copy .config files
  copy:
    src: "../dotfiles/"
    dest: "{{ ansible_env.HOME }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0755'
  tags:
    - update-dotfiles

